### ISSUE TITLE
Make web framework agnostic

### ISSUE THREAD

**Issue by cpursley** [antek-drzewiecki/wine_bouncer#15]
It would be nice to use this with grape with sinatra, grape on rack or [napa](https://github.com/bellycard/napa).

It appears the rails specific portion of this gem is the generator?

**Comment by antek-drzewiecki** [comment]
Hello cpursley,

The code , except for the generator is ruby compliant. Only the Doorkeeper gem, who issues access tokens is build on Rails. I doubt we can remove the rails dependency.

**Comment by cpursley** [comment]
Gotcha, thanks for your nots,

**Comment by Fryie** [comment]
In case anyone stumbles upon this:

I tried setting up doorkeeper without Rails but it seemed too much trouble. So in order not to have to rewrite my entire API in Rails, I just generated a new Rails app within my project:
```
rails new authentication
```
Then I mounted it in my ```config.ru```:
```{ruby}
require 'authentication/config/environment'
map 'oauth' do
  run Authentication::Application
end
```

And I also had to change the scope in the Doorkeeper routes, so they would not end up under 'oauth/oauth/...':
```{ruby}
Rails.application.routes.draw do
  use_doorkeeper scope: ''
end
```

Also had to tweak 2-3 other things, so Rails would load the Gemfile from the parent folder and symlink the database.yml etc., but it turned out to work surprisingly easy.
Now I'm still pulling in a whole Rails app, but at least the whole OAuth server is isolated code-wise.
