### ISSUE TITLE
Any way to break out of wine_bouncer?

### ISSUE THREAD

**Issue by jeffutter** [antek-drzewiecki/wine_bouncer#22]
I was wondering if there is a way to programatically skip over wine_bouncer for a request. I skimmed the code and don't see a way to do it, other than monkey patching some methods. Perhaps I am missing something or my overall approach is incorrect.

My main purpose for this is to have some other backend services to talk to my api. The interactions don't really happen on 'behalf' of a user, so I don't think oauth makes sense (or would really be possible). I need to provide an alternative method for the backend services to authenticate with my api. I was thinking a shared token between the two that could be sent in a header to my grape/wine_bouncer api. However, I would need a way to say "Hey wince_bouncer, this request has a valid admin_token (or whatever), it's AOK, let it continue".

Is there currently any way to do this?

**Comment by jeffutter** [comment]
The best way I've found to handle this is monkey-patch the oauth module like this:

```
module WineBouncer
  class OAuth2
    alias_method :before_original, :before
    def before
      return if env['HTTP_API_TOKEN'] == 'ABC123'
      before_original
    end
  end
end
```

Not sure if this is a reasonable solution. This works for me, for now. If anyone thinks this should be a better supported feature in wine_bouncer let me know and I can come up with a pull request that is more elegant than this hack.

**Comment by antek-drzewiecki** [comment]
Hi @jeffutter , you are right. Winebouncer is made to authenticate against valid tokens that are stored in Doorkeeper. In your case OAuth is possible but sort of overkill if its an internal service, otherwise I would recommend tokens and refresh tokens.

To make things simple for your cause, i would recommend writing your own Grape::Middleware that only implements an before filter.

```
module MyModule
    class TokenAuth < Grape::Middleware::Base
        def before
             raise SomeCustomAuthError unless env['HTTP_API_TOKEN'] == 'ABC123'
        end 
    end 
end
```
and in your Grape API you should catch that error and return an 500 ;)


That might just be the best solution for you?

**Comment by Fryie** [comment]
I used the method mentioned by @jeffutter in order to disable OAuth for specs:
```{ruby}
module WineBouncer
  class OAuth2
    def before; end
  end
end
```

Works quite well!
